version: '3.7'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgresdata: